In [2]:
import pandas as pd
obesity_data_clean = pd.read_csv("obesity_data_clean.csv")

In [3]:
obesity_data_clean.head()

,gender,age,height,weight,family_history,high_cal_diet,freq_veggie,amt_daily_meals,freq_snacking,smoking,amt_water,cal_monitoring,exercise_per_week,time_technology,freq_alcohol,transport,obesity_group,obesity_group_cont
0,female,21.0,1.62,64.0,1,0,2.0,3.0,1,0,2.0,0,0.0,1.0,0,public_transportation,normal_weight,1
1,female,21.0,1.52,56.0,1,0,3.0,3.0,1,1,3.0,1,3.0,0.0,1,public_transportation,normal_weight,1
2,male,23.0,1.80,77.0,1,0,2.0,3.0,1,0,2.0,0,2.0,1.0,2,public_transportation,normal_weight,1
3,male,27.0,1.80,87.0,0,0,3.0,3.0,1,0,2.0,0,2.0,0.0,2,walking,overweight_level_i,2
4,male,22.0,1.78,89.8,0,0,2.0,1.0,1,0,2.0,0,0.0,0.0,1,public_transportation,overweight_level_ii,3